### ISSUE TITLE
Original tensorflow/models version unspecified in documentation

### ISSUE THREAD

**Issue by anthonyhseb** [learningtitans/isbi2017-part3#2]
While the README does mention that this project is a (manual) fork of [tensorflow/models](https://github.com/tensorflow/models), it does not mention the commit ID off of which it had been forked, and due to subsequent commits in [tensorflow/models](https://github.com/tensorflow/models), links to resources within that repo are broken. Mentioning the commit hash in README would help readers alot.

**Comment by dreavjr** [comment]
Thanks for the heads-up! I've amended some of the text and URLs of README.md to solve the broken refs. I didn't save the exact commit from which I've forked (my bad!), but the competition deadline was on March 1st, so that's a good place to look — I've included a link to the last commit on that date.
