### ISSUE TITLE
the more detail about meta-learning svm?

### ISSUE THREAD

**Issue by BUPTAlanMa** [learningtitans/isbi2017-part3#4]
I am reading your paper "RECOD Titans at ISIC Challenge 2017".  You team have did so much experiments and think deeply. I am really impressed on you idea of meta-learning svm. Is It a new scheme of Ensemble learning?  I am nor sure, I guess you concatenating different models' feature and train a  new svm classification? I hope could you give me a more detail introduction or some material? thanks!

**Comment by dreavjr** [comment]
Sorry about the delayed answer — with the semester ending, I'm juggling the roles of researcher, teacher, administrator... :-) I don't think that what we did was particularly novel: we used a scheme sometimes called "stacking" (stacking one model on top of the other, so one model's input is the output of the other). In the case we stacked one SVM meta-model on top of several partial models (some pure Deep Learning, and some already Deep Learning+SVM). The only thing that *might* be novel it the data augmentation on the stacking, in which we sample the bottom models (a lot!) in order to make the meta-model more stable.

Look for "model stacking" + "machine learning" in Google and you'll find a wealth of sources.
